# Generated by Django 4.0.2 on 2022-06-24 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NombreProducto',
            fields=[
                ('idnombreproducto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(default='DEFAULT VALUE', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idproducto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=500)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=15)),
                ('url_producto', models.CharField(max_length=500)),
                ('url_img_producto', models.CharField(max_length=500)),
                ('idnombreproducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webscraping.nombreproducto')),
            ],
        ),
    ]
