# Generated by Django 4.0.2 on 2022-06-25 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webscraping', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='nombre_producto',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='url_img_producto',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='url_producto',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
