# Generated by Django 4.0.2 on 2022-06-25 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webscraping', '0002_alter_producto_nombre_producto_alter_producto_precio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='idnombreproducto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webscraping.nombreproducto'),
        ),
    ]
