# Generated by Django 4.0.2 on 2022-06-25 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webscraping', '0004_alter_producto_nombre_producto_alter_producto_precio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
