# Generated by Django 4.0.2 on 2022-06-25 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webscraping', '0005_alter_producto_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
    ]
