# Generated by Django 4.0.2 on 2022-06-27 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webscraping', '0009_alter_producto_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='idnombreproducto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='webscraping', to='webscraping.nombreproducto'),
        ),
    ]
